[versions]
mod-version = "1.0.0"
jmhPlugin = "0.7.3"
jmh = "1.37"
vanniktech-publish = "0.37.0"

# Fabric (https://fabricmc.net/develop)
minecraft = "26.3"
fabric-loader = "0.19.5"
fabric-api = "0.161.0+26.3"
# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.17-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }

[bundles]
jmh = ["jmh-core", "jmh-generator-annprocess"]
